README: Add note on the requirement for a specific host Docker version
If there is a mismatch between what the build system expects and the
version provided on your host you will see these kinds of errors

Docker Build

```
ERROR: mkfs-hostapp-native-1.0-r0 do_compile: Execution of '/work/build/tmp/work/x86_64-linux/mkfs-hostapp-native/1.0-r0/temp/run.do_compile.1002174' failed with exit code 1
ERROR: Logfile of failure stored in: /work/build/tmp/work/x86_64-linux/mkfs-hostapp-native/1.0-r0/temp/log.do_compile.1002174
Log data follows:
| DEBUG: Executing shell function do_compile
| cgroups: cgroup mountpoint does not exist: unknown
| Error response from daemon: No such image: 8706fc205499
| WARNING: exit code 1 from a shell command.
```

Native Build

"Error response from daemon: Invalid binary format"

Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>